"""Generate the reusable frame and board OBJ meshes for the shelf-sort scene."""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = REPO_ROOT / "assets" / "shelves"


def _box_vertices(center, half_size):
    cx, cy, cz = center
    sx, sy, sz = half_size
    return [
        (cx + x * sx, cy + y * sy, cz + z * sz)
        for x, y, z in (
            (-1, -1, -1),
            (1, -1, -1),
            (1, 1, -1),
            (-1, 1, -1),
            (-1, -1, 1),
            (1, -1, 1),
            (1, 1, 1),
            (-1, 1, 1),
        )
    ]


BOX_FACES = (
    (1, 4, 3, 2),
    (5, 6, 7, 8),
    (1, 2, 6, 5),
    (2, 3, 7, 6),
    (3, 4, 8, 7),
    (4, 1, 5, 8),
)


def _write_obj(path, boxes):
    lines = [
        "# Generated by tests/generate_shelf_mesh.py; do not edit manually.",
        "o shelf",
    ]
    offset = 0
    for name, center, half_size in boxes:
        lines.append(f"# part: {name}")
        lines.extend(
            f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in _box_vertices(center, half_size)
        )
        lines.extend(
            "f " + " ".join(str(offset + index) for index in face) for face in BOX_FACES
        )
        offset += 8
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    frame_boxes = [
        ("post_fl", (-0.17, 0.35, 0.84), (0.025, 0.025, 0.60)),
        ("post_fr", (-0.17, -0.35, 0.84), (0.025, 0.025, 0.60)),
        ("post_bl", (0.17, 0.35, 0.84), (0.025, 0.025, 0.60)),
        ("post_br", (0.17, -0.35, 0.84), (0.025, 0.025, 0.60)),
        ("top", (0.0, 0.0, 1.405), (0.19, 0.38, 0.025)),
        *(
            (f"back_rail_{index}", (0.18, 0.0, z), (0.018, 0.35, 0.025))
            for index, z in enumerate((0.55, 0.875, 1.20), start=1)
        ),
    ]
    board_boxes = [
        *(
            (f"level_{index}", (0.0, 0.0, z), (0.19, 0.38, 0.025))
            for index, z in enumerate((0.43, 0.755, 1.08), start=1)
        ),
    ]
    _write_obj(OUTPUT_DIR / "shelf_frame.obj", frame_boxes)
    _write_obj(OUTPUT_DIR / "shelf_boards.obj", board_boxes)
    table_boxes = [
        ("top", (0.0, 0.0, 0.67), (0.24, 0.27, 0.035)),
        *(
            (f"leg_{x_name}{y_name}", (x, y, 0.405), (0.025, 0.025, 0.23))
            for x_name, x in (("f", -0.19), ("b", 0.19))
            for y_name, y in (("l", 0.22), ("r", -0.22))
        ),
    ]
    _write_obj(OUTPUT_DIR / "side_table.obj", table_boxes)


if __name__ == "__main__":
    main()
